### ISSUE TITLE
Running into  a problem

### ISSUE THREAD

**Issue by ilyes495** [nomanHasan/todoapp-angular#1]
Thank you so much for your tutorial
I cloned your repo and followed the instructions for running, but I kept getting this error

![screenshot from 2017-11-15 13-50-21](https://user-images.githubusercontent.com/17175391/32837115-8e57c58a-ca0c-11e7-8fb8-216f36928ea5.png)

I have a terminal running the backend part and a terminal running ng server, could you please point me out to how to solve the problem 

Thanks

**Comment by nomanHasan** [comment]
Thank you for trying it out. Sorry, I'm not sure why this error happened. Would you please describe the reproducing steps ?
1. `git clone `the projects - `https://github.com/nomanHasan/todo-api` and `https://github.com/nomanHasan/todoapp-angular`
2. Go inside each of them and run `npm install`.
3. Start MongoDB.
4. Run `npm start` in both projects and go to http://localhost:4200

These steps should be enough to start the project. What's your Angular CLI version ?

**Comment by ilyes495** [comment]
I did the steps above, angular side runs successfully as well as the server side, I can see two empty fields with add button, when I try fill the fields and click the button I get the message shown in the image above.
My Angular CLI version is 1.5.0

**Comment by ilyes495** [comment]
Here is the terminals, showing no error, but I think it has to do with angular side
![screenshot from 2017-11-15 17-33-55](https://user-images.githubusercontent.com/17175391/32847860-66f4573c-ca2b-11e7-8fba-9669e1bf260c.png)

**Comment by ghost** [comment]
@nomanHasan  @ilyes495 please help me out from this issue http://prntscr.com/hc1bh9  , i tried to fix this issue from last 24 hours i cant fix this and i have changed some code related with cors and prox-config but i cant fix this issue , i cant insert the data through localhost:4200 url. i have inserted the data directly through mongodb commands that's why we can see the data at top of screen
![pl2pamglrzon4nqrdqozwg 1](https://user-images.githubusercontent.com/28629304/32979848-8a2f60da-cc82-11e7-8bf2-2b46e66938e8.png)
. but i cant insert the data through angular app. please give some suggestion or step by step instruction ...[](url)

**Comment by nomanHasan** [comment]
@aarustar, Sorry I don't know the reason behind the error. First of all I just cloned and setup both Repositories to try it out again. No luck reproducing the error. 

The CORS error shouldn't appear on the console. Because the Content-Type header is added in the CORS configuration. Please check out if you have the CORS configuration correctly (below the mongoose connection code in `app.js`).

`app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  next();
});
`

This should solve the problem. Please let me know If the problem still persists.

**Comment by ghost** [comment]
yes. its my mistake, now its working correctly , thanks for reply
